#!/usr/bin/env ruby

$LOAD_PATH.unshift("#{__dir__}/../lib")

require "rdoc_rubocop"

options, paths = RDocRuboCop::Options.new.parse(ARGV)

paths = ["."] if paths.empty?
paths =
  paths.
  uniq.
  flat_map do |path|
    path = Pathname.new(path)
    if path.directory?
      path.glob(["**/*.c", "**/*.rb"]).sort
    else
      path
    end
  end

runner = RDocRuboCop::RuboCopRunner.new(paths.map(&:to_s), options: options)
runner.run
